#!/usr/bin/env -S uv run --script

import time
import logging
import os
import sys


import threading
import cv2
from numpy import ma
sys.path.append(os.path.dirname(os.path.realpath(__file__))+'/..')
from emioapi import EmioCamera
from emioapi._logging_config import logger
import numpy as np
import triangulation

import tracking
    
def calibrate(camera: EmioCamera, marker_position_dic: dict[int, np.ndarray],marker_size=70):
    # ArUco marker detection setup
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_ARUCO_ORIGINAL)
    parameters = cv2.aruco.DetectorParameters()
    detector = cv2.aruco.ArucoDetector(aruco_dict, parameters)
    NUMBER_OF_FRAMES_TO_CAPTURE = 20

    intrinsics = camera._camera.intr    
    camera_matrix = np.array([
        [intrinsics.fx, 0, intrinsics.ppx],
        [0, intrinsics.fy, intrinsics.ppy],
        [0, 0, 1]
    ], dtype=np.float32)
    dist_coeffs = np.zeros((4, 1))
   
    marker_points = np.array([
                [-marker_size/2, marker_size/2, 0],
                [marker_size/2, marker_size/2, 0],
                [marker_size/2, -marker_size/2, 0],
                [-marker_size/2, -marker_size/2, 0]
            ], dtype=np.float32)
    
    for i in range(NUMBER_OF_FRAMES_TO_CAPTURE): # wait the auto exposure to adjust
        ret, color_frame, depth_frame, depth_rsframe = camera._camera.get_frame()
        
    gray = cv2.cvtColor(color_frame, cv2.COLOR_BGR2GRAY)
    _,thresh_image = cv2.threshold(gray,80,255,cv2.THRESH_TOZERO)
    
    # Detect ArUco markers
    corners, ids, rejected = detector.detectMarkers(thresh_image)
    if ids is None or len(ids) == 0:
        logger.warning(f"No ArUco markers detected for camera {camera.camera_serial}. Calibration failed.")
        return
    
    success = False
    rvec = None
    tvec = None

    obj_points = np.empty((0,3), dtype=np.float32)
    obj_corners = np.empty((0,2), dtype=np.float32)
    for i in range(len(ids)):
        id = int(ids[i][0])
        # 3D object points of marker corners

        if id in marker_position_dic.keys():
            marker_position = marker_position_dic[id]
            obj_points = np.vstack([obj_points, marker_points + marker_position])
            obj_corners = np.vstack([obj_corners, [corners[i][0][j] for j in range(4)]])
            logger.info(f"Camera {camera.camera_serial} detected marker {id} at position {marker_position}.")

        
    if len(obj_points) > 0:
        success, rvec, tvec = cv2.solvePnP(
            obj_points,
            obj_corners,
            camera_matrix,
            dist_coeffs,
        )

    if success and rvec is not None and tvec is not None:
        rotation_matrix, _ = cv2.Rodrigues(rvec)
        # location of the camera in the marker reference frame is given by -R^T * tvec
        camera_position = -rotation_matrix.T @ tvec.flatten()
        # camera orientation in the marker reference frame is given by R^T
        camera_orientation = rotation_matrix.T


        camera._camera.position_estimator.R = camera_orientation
        camera._camera.position_estimator.t = camera_position
        logger.debug(f"Camera {camera.camera_serial} position estimator set with R:\n{rotation_matrix.T}\nt:\n{camera_position}")
    logger.info(f"Camera {camera.camera_serial} calibrated.")


def create_marker_position_dictionary():
    # Create a dictionary to store the positions of the markers
    marker_positions = {
        672: np.array([0, 0, 0]),  # Marker ID 672 at the origin
        42: np.array([84, 0, 0]),  # Marker ID 42 at (84mm, 0, 0)
        # Add more markers here if needed
    }
    return marker_positions


def run_camera(camera: EmioCamera,synchronization_barrier: threading.Barrier):
    while camera.is_running:
        camera.update()  # update the camera frame and trackers
            # Wait for all threads to reach this point before proceeding
        synchronization_barrier.wait()


def main(cameras: list[EmioCamera]):
    logger.info("Calibrating cameras...")
    calibration_threads = []
    start_time = time.time()
    marker_position_dic = create_marker_position_dictionary()
    
    for camera in cameras:
        calibration_thread = threading.Thread(target=calibrate, args=(camera,marker_position_dic))
        calibration_threads.append(calibration_thread)
        calibration_thread.start()
        #calibrate(camera,marker_position_dic)


    for calibration_thread in calibration_threads:
        calibration_thread.join()

    logger.info(f"Calibration completed in {time.time() - start_time:.2f} seconds.")
    input("Press Enter to start pose estimation...")


    synchronization_barrier = threading.Barrier(len(cameras)+1)
    run_camera_threads = []
    for camera in cameras:
        thread = threading.Thread(target=run_camera, args=(camera, synchronization_barrier))
        thread.daemon = True  # Set the thread as a daemon thread
        run_camera_threads.append(thread)
        thread.start()

    Rs, Ts, Ks = build_camera_matrices(cameras)

    tracker = tracking.MultiMarkerTracker3D(
    dist_gate=15,    # à tuner selon la vitesse max et dt=1/30
    max_misses=5,      # tolère ~5 frames d'occlusion
    q=1e-2,
    r=1e-4
    )
    t = 0.0
    dt = 0.1

    while cameras[0].is_running:  # Assuming all cameras have the same running state
        try:
            
            # for camera in cameras:
            #     camera.update()  # update the camera frame and trackers
            synchronization_barrier.wait()  # Wait for all camera threads to update before proceeding
            matches = marker_position_estimation(cameras, Ks, Rs, Ts)

            X_meas = []  # list of 3D points measured at this frame
            if matches is None:
                continue
            
            for m in matches:
                Xk = m["X"]
                Rms = m["rms"]

                if Rms < 3.0:  # gate reprojection
                    X_meas.append(Xk)

            tracks = tracker.update(X_meas, t)
            t += dt

            visualize_matches(cameras, matches, Ks, Rs, Ts)
            visualize_tracks(cameras, tracks, Ks, Rs, Ts)
            cv2.waitKey(1)
            time.sleep(dt) # to run at ~1/dt Hz, adjust as needed
        except KeyboardInterrupt:
            logger.info("Keyboard interrupt received.")
            break
        except Exception as e:
            logger.exception(f"Error during communication: {e}")
            break

    synchronization_barrier.abort()

def build_camera_matrices(cameras):
    Rs = []
    Ts = []
    Ks = []
    for id_camera in range(len(cameras)):
        camera = cameras[id_camera]
                # Always add camera parameters, even if no trackers
        R_cw = camera._camera.position_estimator.R.T
        t_cw = -R_cw @ camera._camera.position_estimator.t.reshape(3, 1)
        Rs.append(R_cw)
        Ts.append(t_cw)
        intrinsics = camera._camera.intr    
        camera_matrix = np.array([
                    [intrinsics.fx, 0, intrinsics.ppx],
                    [0, intrinsics.fy, intrinsics.ppy],
                    [0, 0, 1]
                        ], dtype=np.float32)
        Ks.append(camera_matrix)
    return Rs,Ts,Ks

    

def marker_position_estimation(cameras, Ks, Rs, Ts):
    current_time = time.time()
    logger.info(f"Camera update time: {time.time() - current_time:.4f} seconds")

    info = f"Count tracker: "
    for camera in cameras:
        info += f"{len(camera.trackers_pos)},"
    logger.info(info)
    current_time = time.time()
    rays = []
    uvs = []
    
    detections = [[] for _ in range(len(cameras))] # list of list of (u,v) in pixels for each camera
    for id_camera in range(len(cameras)):
        camera = cameras[id_camera]
                # Always add camera parameters, even if no trackers
                
        if len(camera.trackers_pos) > 0:
            x = camera._trackers_pos_camera_image[0][0]
            y = camera._trackers_pos_camera_image[0][1]
            rays.append(triangulation.ray(camera._camera.position_estimator.t, camera._camera.position_estimator.camera_image_to_simulation(x, y, 1.0) - camera._camera.position_estimator.t))
            uvs.append((x, y))
            logger.info(f"Trackers positions Camera {camera.camera_serial}: {np.round(camera.trackers_pos[0], decimals=2)}")
        for tracker in camera._trackers_pos_camera_image:
            detections[id_camera].append((tracker[0],tracker[1]))    


    current_time = time.time()    
    estimation_nview, estimation_errors_nv = triangulation.triangulate_nview(
                Ks, 
                Rs, 
                Ts, 
                uvs, robust=True
            )
    
    logger.info(f"Triangulation with LM refinement time: {time.time() - current_time:.4f} seconds")
    if estimation_nview is not None:
        logger.info(f"Triangulated position with LM refinement: {np.round(estimation_nview.T, decimals=2)}")
        logger.info(f"Reprojection error with LM refinement: {np.round(np.array(estimation_errors_nv['rms_reproj_px']), decimals=2)} pixels")
    current_time = time.time()
    estimation, estimation_errors = triangulation.point_closest_to_rays(rays)
    logger.info(f"QP Triangulation time: {time.time() - current_time:.4f} seconds")
    if estimation is not None:
        logger.info(f"QP Triangulated position: {np.round(estimation.T, decimals=2)}")
        logger.info(f"QP Point to rays error: {np.round(estimation_errors, decimals=2)}") 


            # detections[c] = list of (u,v) in pixels for camera c at current frame
    current_time = time.time()
    matches = triangulation.match_ncams_one_frame(detections, Ks, Rs, Ts,
                               ref=0,
                               epi_gate_px=20.0,
                               reproj_gate_px=20.0,
                               beam_width=50,
                               min_views=2)
    logger.info(f"Matches: {len(matches)}")
    logger.info(f"Matching time: {time.time() - current_time:.4f} seconds")


    return matches

def visualize_matches(cameras, matches, Ks, Rs, Ts):
    for id_camera in range(len(cameras)):
        camera = cameras[id_camera]
        image = camera._camera.frame.copy()
        for i in range(len(matches)):
            m = matches[i]
            logger.info(f"Match {i}: views: {m['views']}, rms: {m['rms']}, idx_map: {m['idx']}, X: {m['X']}")
            # find in m['idx'] the index of the view corresponding to id_camera
            for idx_view, view in enumerate(m["idx"]):
                if view == 1:
                    Ps = triangulation.make_projection(Ks[id_camera], Rs[id_camera], Ts[id_camera])
                    x = triangulation.project_point(Ps, m["X"])
                    u_proj = int(x[0]) 
                    v_proj = int(x[1]) 
                    cv2.circle(image, (u_proj, v_proj), 20, (255, 0, 0), 4)
                    cv2.putText(image, f"ID {i}", (u_proj+20, v_proj), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 0, 0), 1)

        cv2.imshow(f"Camera {camera.camera_serial} matches", image)

    
def visualize_tracks(cameras, tracks, Ks, Rs, Ts):
    for id_camera in range(len(cameras)):
        camera = cameras[id_camera]
        image = camera._camera.frame.copy()
        for track in tracks:
            logger.info(f"Track: {track}")
            Ps = triangulation.make_projection(Ks[id_camera], Rs[id_camera], Ts[id_camera])
            x = triangulation.project_point(Ps, track['pos'])
            u_proj = int(x[0]) 
            v_proj = int(x[1]) 
            cv2.circle(image, (u_proj, v_proj), 10, (0, 255, 0), 2)
            cv2.putText(image, f"ID {track['id']}", (u_proj+10, v_proj+10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)
        cv2.imshow(f"Camera {camera.camera_serial} tracks", image)


if __name__ == "__main__":
   
    try:
        logger.info("List of available cameras\n"+str(EmioCamera.listCameras()))

        logger.info("Opening and configuring EMIO Camera...")

        camera = EmioCamera(show=False, track_markers=True, compute_point_cloud=True)
        
        cameras_sn = camera.listCameras()
        cameras = []
        for sn in cameras_sn:
            logger.info(f"Camera SN: {sn}")
            cameras.append(EmioCamera(sn, show=False, track_markers=True, compute_point_cloud=False))
        for camera in cameras:
            camera._camera.height = 720
            camera._camera.width = 1280
            camera.fps = 30 # sets the fps to 30. Default is 60 and can only be one of 30. 60 or 90fps
            camera.depth_max = 600 # sets the maximum depth to 600mm. Default is 430mm
            camera.depth_min = 0 # sets the minimum depth to 0mm. Default is 2mm
            camera.open(camera.camera_serial)
            logger.info(f"Emio camera {camera.camera_serial} opened.")
        
        main(cameras)

        logger.info("Main function completed.")
        logger.info("Closing Emio API...")

        for camera in cameras:
            camera.close()
            logger.info(f"Emio camera {camera.camera_serial} closed.")
        logger.info("EMIO API closed.")
    except Exception as e:
        logger.exception(f"An error occurred: {e}")
        for camera in cameras:
            try:
                camera.close()
            except Exception as close_e:
                logger.exception(f"An error occurred while closing camera {camera.camera_serial}: {close_e}")
