#!/usr/bin/env -S uv run --script

import time
import logging
import os
import sys
from qpsolvers import Problem, solve_problem, available_solvers


sys.path.append(os.path.dirname(os.path.realpath(__file__))+'/..')
from emioapi import EmioCamera
from emioapi._logging_config import logger
import numpy as np

class ray:
    def __init__(self,origin,direction):
        self.origin = origin
        self.direction = direction/np.linalg.norm(direction)

def triangulate(rays: list[ray]):
    """
    Solve the quadratic programming problem:
        minimize (1/2) x^T P x + q^T x
        subject to A x = b
                   G x <= h
                   lb <= x <= ub    
    Args:        rays: list of rays, each ray is defined by an origin and a direction
    Returns:        x: Solution vector (3,) the triangulated position
                    errors: list of errors for each ray, the distance from the triangulated position to the ray
    """
    R = np.zeros((len(rays),3,3+len(rays)))
    P = np.zeros((3+len(rays),3+len(rays)))
    q = np.zeros((3+len(rays),))
    for i in range(len(rays)):
        R[i][0:3,0:3] = np.eye(3)
        R[i][0:3,3+i] = -rays[i].direction   
        P += R[i].T @ R[i]
        q += -R[i].T @ rays[i].origin

    problem = Problem(P, q)
    solution = solve_problem(problem, solver="clarabel")
    # Use the OSQP solver as an example. You can choose any other solver available in qpsolvers.
    if (solution.x is None):
        logger.warning("QP solver failed to find a solution.")
        return None,None   
    
    errors = []
    for i in range(len(rays)):
        error = np.linalg.norm(R[i] @ solution.x - rays[i].origin)
        errors.append(error)
  
    
    return solution.x[0:3],errors
    


def main(cameras: list[EmioCamera]):
    logger.info("Calibrating cameras...")
    for camera in cameras:
        camera.calibrate()  # calibrate the camera if needed
        logger.info(f"Camera {camera.camera_serial} calibrated.")

    while cameras[0].is_running:  # Assuming all cameras have the same running state
        try:

            for camera in cameras:
                camera.update()  # update the camera frame and trackers

            print("-"*20)
            logger.info(f"Count tracker: {len(cameras[0].trackers_pos)},{len(cameras[1].trackers_pos)},{len(cameras[2].trackers_pos)}")

            rays = []
            for camera in cameras:
                if len(camera.trackers_pos) > 0:
                    x = camera._trackers_pos_camera_image[0][0]
                    y = camera._trackers_pos_camera_image[0][1]
                    rays.append(ray(camera._camera.position_estimator.t, camera._camera.position_estimator.camera_image_to_simulation(x, y, 1.0) - camera._camera.position_estimator.t))
                    logger.info(f"Trackers positions Camera {camera.camera_serial}: {np.round(camera.trackers_pos[0], decimals=2)}")

            estimation, estimation_errors = triangulate(rays)
            if estimation is not None:
                logger.info(f"Triangulated position: {np.round(estimation.T, decimals=2)}")
                logger.info(f"Errors: {estimation_errors}")

            time.sleep(0.1)
        except KeyboardInterrupt:
            logger.info("Keyboard interrupt received.")
            break
        except Exception as e:
            logger.exception(f"Error during communication: {e}")
            break


if __name__ == "__main__":
   
    try:
        logger.info("List of available cameras\n"+str(EmioCamera.listCameras()))

        logger.info("Opening and configuring EMIO Camera...")

        camera = EmioCamera(show=False, track_markers=True, compute_point_cloud=True)
        
        cameras_sn = camera.listCameras()
        cameras = []
        for sn in cameras_sn:
            logger.info(f"Camera SN: {sn}")
            cameras.append(EmioCamera(sn, show=False, track_markers=True, compute_point_cloud=False))
        for camera in cameras:
            camera.fps = 60 # sets the fps to 30. Default is 60 and can only be one of 30. 60 or 90fps
            camera.depth_max = 600 # sets the maximum depth to 600mm. Default is 430mm
            camera.depth_min = 0 # sets the minimum depth to 0mm. Default is 2mm
            camera.open(camera.camera_serial)
            logger.info(f"Emio camera {camera.camera_serial} opened.")
        
        main(cameras)

        logger.info("Main function completed.")
        logger.info("Closing Emio API...")

        for camera in cameras:
            camera.close()
            logger.info(f"Emio camera {camera.camera_serial} closed.")
        logger.info("EMIO API closed.")
    except Exception as e:
        logger.exception(f"An error occurred: {e}")
        for camera in cameras:
            try:
                camera.close()
            except Exception as close_e:
                logger.exception(f"An error occurred while closing camera {camera.camera_serial}: {close_e}")
