#!/usr/bin/env -S uv run --script

import time
import logging
import os
import sys
from qpsolvers import Problem, solve_problem, available_solvers


sys.path.append(os.path.dirname(os.path.realpath(__file__))+'/..')
from emioapi import EmioCamera
from emioapi._logging_config import logger
import numpy as np

def solve_qp(r1,r2,q1,q2):
    """
    Solve the quadratic programming problem:
        minimize (1/2) x^T P x + q^T x
        subject to A x = b
                   G x <= h
                   lb <= x <= ub

    Args:
        P: Quadratic coefficient matrix (n x n)
        q: Linear coefficient vector (n,)
        A: Equality constraint matrix (m x n)
        b: Equality constraint vector (m,)
        G: Inequality constraint matrix (p x n)
        h: Inequality constraint vector (p,)
        lb: Lower bound vector (n,)
        ub: Upper bound vector (n,)

    Returns:
        x: Solution vector (n,)
    """
    R = np.hstack((r1,-r2))
    P = R.T @ R
    q = R.T @ (q1 - q2)
    
    A=None
    b=None
    G=None
    h=None
    lb=None
    ub=None
    problem = Problem(P, q, G, h, A, b, lb, ub)
    solution = solve_problem(problem, solver="clarabel")
    # Use the OSQP solver as an example. You can choose any other solver available in qpsolvers.
    s1 = solution.x[0]
    s2 = solution.x[1]
    return r1*s1+q1,r2*s2+q2

def solve_qp_global(r1,r2,q1,q2):
    """
    Solve the quadratic programming problem:
        minimize (1/2) x^T P x + q^T x
        subject to A x = b
                   G x <= h
                   lb <= x <= ub

    Args:
        P: Quadratic coefficient matrix (n x n)
        q: Linear coefficient vector (n,)
        A: Equality constraint matrix (m x n)
        b: Equality constraint vector (m,)
        G: Inequality constraint matrix (p x n)
        h: Inequality constraint vector (p,)
        lb: Lower bound vector (n,)
        ub: Upper bound vector (n,)

    Returns:
        x: Solution vector (n,)
    """
    z = np.zeros_like(r1)
    R1 = np.hstack((np.eye(3),-r1,z))
    R2 = np.hstack((np.eye(3),z,-r2))
    
    P = R1.T @ R1 + R2.T @ R2
    q = -R1.T @ q1 - R2.T @ q2
    A=None
    b=None
    G=None
    h=None
    lb=None
    ub=None
    problem = Problem(P, q, G, h, A, b, lb, ub)
    solution = solve_problem(problem, solver="clarabel")
    # Use the OSQP solver as an example. You can choose any other solver available in qpsolvers.
    qa = solution.x[0:3]
    
    return qa 


def main(emio: EmioCamera,emio2: EmioCamera):

    emio.calibrate()  # calibrate the camera if needed
    emio2.calibrate()  # calibrate the camera if needed

    while emio.is_running:
        try:
            emio.update() # update the camera frame and trackers
            emio2.update() # update the camera frame and trackers

            print("-"*20)
            logger.info(f"Count tracker: {len(emio.trackers_pos)},{len(emio2.trackers_pos)}")
            
            logger.info(f"Trackers positions Camera 1: {np.round(emio.trackers_pos, decimals=2)}")
            logger.info(f"Trackers positions Camera 2: {np.round(emio2.trackers_pos, decimals=2)}")
            
            x = emio._trackers_pos_camera_image[0][0]
            y = emio._trackers_pos_camera_image[0][1]
            ray_world_1 = np.array([emio._camera.position_estimator.camera_image_to_simulation(x, y, 1.0) - emio._camera.position_estimator.t])
            camera_pos_world = emio._camera.position_estimator.t
            q1 = np.array([emio._camera.position_estimator.t])
            
            x = emio2._trackers_pos_camera_image[0][0]
            y = emio2._trackers_pos_camera_image[0][1]
            ray_world_2 = np.array([emio2._camera.position_estimator.camera_image_to_simulation(x, y, 1.0) - emio2._camera.position_estimator.t])
            camera_pos_world_2 = emio2._camera.position_estimator.t
            q2 = np.array([emio2._camera.position_estimator.t])
            
            estimation1,estimation2 = solve_qp(ray_world_1.T,ray_world_2.T,q1.T,q2.T)
            logger.info(f"Trackers positions Camera 1: {np.round(estimation1.T, decimals=2)}")
            logger.info(f"Trackers positions Camera 2: {np.round(estimation2.T, decimals=2)}")
            estimation3 = solve_qp_global(ray_world_1.T,ray_world_2.T,q1.T,q2.T)
            logger.info(f"Trackers positions Camera  : {np.round(estimation3.T, decimals=2)}")

    

            time.sleep(0.1)
        except KeyboardInterrupt:
            logger.info("Keyboard interrupt received.")
            break
        except Exception as e:
            logger.exception(f"Error during communication: {e}")
            break


if __name__ == "__main__":
   
    try:
        logger.info("List of available cameras\n"+str(EmioCamera.listCameras()))

        logger.info("Opening and configuring EMIO Camera...")

        emio = EmioCamera(show=False, track_markers=True, compute_point_cloud=True)
        emio.fps = 60 # sets the fps to 30. Default is 60 and can only be one of 30. 60 or 90fps
        emio.depth_max = 600 # sets the maximum depth to 600mm. Default is 430mm
        emio.depth_min = 0 # sets the minimum depth to 0mm. Default is 2mm


        emio2 = EmioCamera(show=False, track_markers=True, compute_point_cloud=True)
        emio2.fps = 60 # sets the fps to 30. Default is 60 and can only be one of 30. 60 or 90fps
        emio2.depth_max = 600 # sets the maximum depth to 600mm. Default is 430mm
        emio2.depth_min = 0 # sets the minimum depth to 0mm. Default is 2mm
        cameras = emio.listCameras()


        if emio.open(cameras[1]): # This will open the first available Realsense camera
            logger.info(f"Emio camera {emio.camera_serial} opened.")
            logger.info("Running main function...")
            emio2.open(cameras[0])
            logger.info(f"Emio camera {emio2.camera_serial} opened.")
            logger.info("Running main function...")
            
            main(emio,emio2)

            logger.info("Main function completed.")
            logger.info("Closing Emio API...")

            emio.close()
            emio2.close()
            logger.info("EMIO API closed.")
    except Exception as e:
        logger.exception(f"An error occurred: {e}")
